from app.models.attendance import Attendance
from app.models.attendance_detail import AttendanceDetail
from app.models.audit_log import AuditLog
from app.models.course import Course
from app.models.department import Department
from app.models.exam import Exam
from app.models.faculty import Faculty
from app.models.fee import Fee
from app.models.mark import Mark
from app.models.notification import Notification
from app.models.payment import Payment
from app.models.role import Role
from app.models.student import Student
from app.models.student_course import StudentCourse
from app.models.subject import Subject
from app.models.user import User
